/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface LoveQuote {
  'id' : string,
  'text' : string,
  'author' : [] | [string],
}
export interface PhotoEntry {
  'id' : string,
  'order' : bigint,
  'blob' : ExternalBlob,
  'caption' : string,
}
export interface Shayari {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'body' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLoveQuote' : ActorMethod<[LoveQuote], undefined>,
  'addPhotoEntry' : ActorMethod<[PhotoEntry], undefined>,
  'addShayari' : ActorMethod<[Shayari], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteLoveQuote' : ActorMethod<[string], undefined>,
  'deletePhotoEntry' : ActorMethod<[string], undefined>,
  'deleteShayari' : ActorMethod<[string], undefined>,
  'editLoveQuote' : ActorMethod<[LoveQuote], undefined>,
  'editPhotoEntry' : ActorMethod<[PhotoEntry], undefined>,
  'editShayari' : ActorMethod<[Shayari], undefined>,
  'getAllLoveQuotes' : ActorMethod<[], Array<LoveQuote>>,
  'getAllPhotoEntries' : ActorMethod<[], Array<PhotoEntry>>,
  'getAllShayari' : ActorMethod<[], Array<Shayari>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLoveQuoteById' : ActorMethod<[string], [] | [LoveQuote]>,
  'getPhotoEntryById' : ActorMethod<[string], [] | [PhotoEntry]>,
  'getShayariById' : ActorMethod<[string], [] | [Shayari]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];