/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LoveQuote = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'author' : IDL.Opt(IDL.Text),
});
export const PhotoEntry = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'dataUrl' : IDL.Text,
  'mimeType' : IDL.Text,
  'caption' : IDL.Text,
});
export const Shayari = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'body' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLoveQuote' : IDL.Func([LoveQuote], [], []),
  'addPhotoEntry' : IDL.Func([PhotoEntry], [], []),
  'addShayari' : IDL.Func([Shayari], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, IDL.Variant({ 'admin': IDL.Null, 'user': IDL.Null, 'guest': IDL.Null })], [], []),
  'deleteLoveQuote' : IDL.Func([IDL.Text], [], []),
  'deletePhotoEntry' : IDL.Func([IDL.Text], [], []),
  'deleteShayari' : IDL.Func([IDL.Text], [], []),
  'editLoveQuote' : IDL.Func([LoveQuote], [], []),
  'editPhotoEntry' : IDL.Func([PhotoEntry], [], []),
  'editShayari' : IDL.Func([Shayari], [], []),
  'getAllLoveQuotes' : IDL.Func([], [IDL.Vec(LoveQuote)], ['query']),
  'getAllPhotoEntries' : IDL.Func([], [IDL.Vec(PhotoEntry)], ['query']),
  'getAllShayari' : IDL.Func([], [IDL.Vec(Shayari)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLoveQuoteById' : IDL.Func([IDL.Text], [IDL.Opt(LoveQuote)], ['query']),
  'getPhotoEntryById' : IDL.Func([IDL.Text], [IDL.Opt(PhotoEntry)], ['query']),
  'getShayariById' : IDL.Func([IDL.Text], [IDL.Opt(Shayari)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LoveQuote = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'author' : IDL.Opt(IDL.Text),
  });
  const PhotoEntry = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'dataUrl' : IDL.Text,
    'mimeType' : IDL.Text,
    'caption' : IDL.Text,
  });
  const Shayari = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'body' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLoveQuote' : IDL.Func([LoveQuote], [], []),
    'addPhotoEntry' : IDL.Func([PhotoEntry], [], []),
    'addShayari' : IDL.Func([Shayari], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLoveQuote' : IDL.Func([IDL.Text], [], []),
    'deletePhotoEntry' : IDL.Func([IDL.Text], [], []),
    'deleteShayari' : IDL.Func([IDL.Text], [], []),
    'editLoveQuote' : IDL.Func([LoveQuote], [], []),
    'editPhotoEntry' : IDL.Func([PhotoEntry], [], []),
    'editShayari' : IDL.Func([Shayari], [], []),
    'getAllLoveQuotes' : IDL.Func([], [IDL.Vec(LoveQuote)], ['query']),
    'getAllPhotoEntries' : IDL.Func([], [IDL.Vec(PhotoEntry)], ['query']),
    'getAllShayari' : IDL.Func([], [IDL.Vec(Shayari)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLoveQuoteById' : IDL.Func([IDL.Text], [IDL.Opt(LoveQuote)], ['query']),
    'getPhotoEntryById' : IDL.Func([IDL.Text], [IDL.Opt(PhotoEntry)], ['query']),
    'getShayariById' : IDL.Func([IDL.Text], [IDL.Opt(Shayari)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
