/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const LoveQuote = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'author' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PhotoEntry = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'blob' : ExternalBlob,
  'caption' : IDL.Text,
});
export const Shayari = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'body' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLoveQuote' : IDL.Func([LoveQuote], [], []),
  'addPhotoEntry' : IDL.Func([PhotoEntry], [], []),
  'addShayari' : IDL.Func([Shayari], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteLoveQuote' : IDL.Func([IDL.Text], [], []),
  'deletePhotoEntry' : IDL.Func([IDL.Text], [], []),
  'deleteShayari' : IDL.Func([IDL.Text], [], []),
  'editLoveQuote' : IDL.Func([LoveQuote], [], []),
  'editPhotoEntry' : IDL.Func([PhotoEntry], [], []),
  'editShayari' : IDL.Func([Shayari], [], []),
  'getAllLoveQuotes' : IDL.Func([], [IDL.Vec(LoveQuote)], ['query']),
  'getAllPhotoEntries' : IDL.Func([], [IDL.Vec(PhotoEntry)], ['query']),
  'getAllShayari' : IDL.Func([], [IDL.Vec(Shayari)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLoveQuoteById' : IDL.Func([IDL.Text], [IDL.Opt(LoveQuote)], ['query']),
  'getPhotoEntryById' : IDL.Func([IDL.Text], [IDL.Opt(PhotoEntry)], ['query']),
  'getShayariById' : IDL.Func([IDL.Text], [IDL.Opt(Shayari)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const LoveQuote = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'author' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PhotoEntry = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'blob' : ExternalBlob,
    'caption' : IDL.Text,
  });
  const Shayari = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'body' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLoveQuote' : IDL.Func([LoveQuote], [], []),
    'addPhotoEntry' : IDL.Func([PhotoEntry], [], []),
    'addShayari' : IDL.Func([Shayari], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLoveQuote' : IDL.Func([IDL.Text], [], []),
    'deletePhotoEntry' : IDL.Func([IDL.Text], [], []),
    'deleteShayari' : IDL.Func([IDL.Text], [], []),
    'editLoveQuote' : IDL.Func([LoveQuote], [], []),
    'editPhotoEntry' : IDL.Func([PhotoEntry], [], []),
    'editShayari' : IDL.Func([Shayari], [], []),
    'getAllLoveQuotes' : IDL.Func([], [IDL.Vec(LoveQuote)], ['query']),
    'getAllPhotoEntries' : IDL.Func([], [IDL.Vec(PhotoEntry)], ['query']),
    'getAllShayari' : IDL.Func([], [IDL.Vec(Shayari)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLoveQuoteById' : IDL.Func([IDL.Text], [IDL.Opt(LoveQuote)], ['query']),
    'getPhotoEntryById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PhotoEntry)],
        ['query'],
      ),
    'getShayariById' : IDL.Func([IDL.Text], [IDL.Opt(Shayari)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };